#!/bin/bash

SD=`date "+%Y/%m/%d"`
addr="255.255.255.255/1"
timeGap="3600"

meta=`rwfilter --start-date=$SD --any-address=$addr --pass=stdout --type=all |\
rwcount --bin-size=$timeGap -delimited=, --no-titles | cut -d "," -f1,3|\
sed "s/\(.*\),\(.*\)/['\1',\2],/g" | sed '$s/,$//' | sed "s/. \([A-Za-z].*\)],/,'\1'],/g"`

Chartcode="
<html>
<head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
                ['Date','Bytes'],
                $meta
        ]);


        var options = {
          title: 'Traffic per Hourly',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));
        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="curve_chart" style='width: 900px; height: 500px'></div>
  </body>
</html>"
echo "$Chartcode" > HourlyChart.html
